pr: none

trigger:
  branches:
    include:
      - master
pool:
  name: default


jobs:
  - job: test
    displayName: 'Demo app internship project'
    workspace:
      clean: all
    steps:
      - template: 'build push image.yml'
      - template: 'scan image.yml'
      - template: 'scan code vul secret config.yml'
      - template: 'publish.yml'
      - template: 'dependencycheck.yml'
