steps:
  - script: |
        docker run --name trivycodescanner aquasec/trivy fs --scanners vuln,secret,config --format sarif -o ./trivycodescan.sarif .
        docker cp trivycodescanner:trivycodescan.sarif $(Pipeline.Workspace)
        docker rm -f trivycodescanner

    displayName: 'Trivy code scan'